<a href="https://colab.research.google.com/github/sajedefadaei/Pytorch-Tutorial/blob/main/Pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Torch

In [1]:
import torch
import numpy as np

In [3]:
np1 = np.random.randn(3, 4)
np1

array([[ 0.40715576, -1.07933319,  0.51903808, -0.34581382],
       [ 0.05169937,  0.1919759 , -0.48090449, -0.16250871],
       [-1.12393355,  1.19390789,  0.01365577, -0.33815374]])

In [5]:
np1.dtype

dtype('float64')

In [7]:
tens_2d = torch.randn(3,4)
tens_2d

tensor([[-1.1347, -0.3343,  1.7052, -0.0266],
        [ 0.0173, -0.7570, -0.3943, -1.3493],
        [-0.4250, -0.9449,  0.0603,  0.0203]])

In [13]:
tens_3d = torch.zeros(2,3,4)
tens_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
# converting numpy to tensor
tens_np = torch.tensor(np1)
tens_np

tensor([[ 0.4072, -1.0793,  0.5190, -0.3458],
        [ 0.0517,  0.1920, -0.4809, -0.1625],
        [-1.1239,  1.1939,  0.0137, -0.3382]], dtype=torch.float64)

In [17]:
torch2d2 = torch.ones((2,3), dtype=torch.float64, device="cuda:0")
torch2d2

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)

# Torch Operation

## Slicing

In [4]:
my_torch1 = torch.arange(15)
my_torch1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
my_torch2 = my_torch1.reshape(3, 5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [8]:
my_torch3 = my_torch1.view(3, 5)
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [9]:
my_torch4 = my_torch1.reshape(3, -1)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [11]:
my_torch5 = my_torch1.reshape(-1, 5)
my_torch5

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [20]:
my_torch5[:,3]

tensor([ 3,  8, 13])

In [25]:
my_torch5[:,3:]

tensor([[ 3,  4],
        [ 8,  9],
        [13, 14]])